### PR TITLE
WIP: Configuring SSD

### PR DESCRIPTION
**Pull request by abalfoort**
Module to configure SSD: ssdcfg.

This is a work in progress. So, I need some feedback on this. Especially how to make this work on all distro flavors.

This module enables fstrim, configures swappiness and sets the IO scheduler.

FIXES [#1987](https://github.com/calamares/calamares/issues/1987)

### CODE REVIEW

**Comment by kkofler** [comment]
The `backend` setting in the `.conf` file is bogus (copied from `packages`, where it makes sense; here, it does not).

**Comment by abalfoort** [comment]
Indeed, this is currently not used. I'm still looking for a way to install sysfsutils if needed.

I have no way of adding sysfsutils to the list of packages to be installed by the packages module.

**Comment by adriaandegroot** [comment]
The config file and schema seem to be mismatched; what is all that packaging setting doing there? The schema mentions *grubcfg*. Does is validate the current config file? Because vm.something looks like a dubious key to me.

**Comment by adriaandegroot** [comment]
You **can** manipulate the packages-to-install: it's just a GS object, so you can treat it like a dict in Python. But it will be messy and unpleasant. More effective would be two issues / PRs against Calamares itself:

- "Expose request_install_package() to Python", which would add that function to the Python API. That means adding a function to `PythonJobAPI.h` that does the work from C++ (I would suggest, for simplicity, to take a string or a list of strings; expand the api in `libcalamares/packages/Globals.h` to also **add** to an existing package-set, and pass the module-id from the Python job there as a C++ implementation detail)
- "Allow filtering *packages* runs." It might be useful to have the package module install only packages added through a specific *source*. That's part of the C++ api, where lists of packages are added from a specific source. So you could say something like "install the packages that were requested by module *a-name*", which would allow package-installation to proceed in phases.

**Comment by abalfoort** [comment]
Thanks. My C++ knowledge is limited but I'll take a look at it after the holidays.

**Pull request closed without merging**
